# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.{default}/":
    type: upstream
    upstream: "netflix:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

    "https://www.main-bvxea6i-o7lih3c63ivgw.de-2.platformsh.site":
    type: upstream
    upstream: "netflix:http"

"https://main-bvxea6i-o7lih3c63ivgw.de-2.platformsh.site":
    type: redirect
    to: "https://www.main-bvxea6i-o7lih3c63ivgw.de-2.platformsh.site"
